apiVersion: v1
kind: ReplicationController
metadata:
  name: contacts-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: contacts-api
    spec:
      containers:
        - name: contacts-api
          image: CONTACTS_API_IMAGE
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: contacts
            - name: DB_USERNAME
              value: test
            - name: DB_PASSWORD
              value: test
          ports:
            - containerPort: 3000
