apiVersion: v1
kind: ReplicationController
metadata:
  name: contacts-ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: contacts-ui
    spec:
      containers:
        - name: CONTACTS_APP_NAME
          image: CONTACTS_UI_IMAGE
          ports:
            - containerPort: 3000
              name: npm
            - containerPort: 80
              name: http
          imagePullPolicy: Always