apiVersion: v1
kind: ReplicationController
metadata:
  name: CONTACTS_APP_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: CONTACTS_APP_NAME
    spec:
      containers:
        - name: CONTACTS_APP_NAME
          image: CONTACTS_UI_IMAGE
          ports:
            - containerPort: 3000
              name: npm
            - containerPort: 80
              name: http
          imagePullPolicy: Always